### ISSUE TITLE
Lets Discuss

### ISSUE THREAD

**Issue by ashutosh7i** [SayantaniDeb/Project-name-to-be-decided-#2]
## Before starting, lets discuss few things,
1. Features our website should have.
2. Name.
3. Technology stack

**Comment by arnabnandy7** [comment]
Bump for the notification.

**Comment by SrijanDas** [comment]
Suggestions
- Tech Stack - **Nextjs, Tailwind-css, mongodb**
- Name: **Tech Swayamvar**
I think he suggested a really cool name😅
![Screenshot_2023-04-12-23-33-18-182-edit_com twitter android](https://user-images.githubusercontent.com/53689208/231545285-c41a9ba2-a8cf-42a8-99a8-6573f8d47f7d.jpg)

**Comment by subhams56** [comment]
-Styling Tailwind if possible

**Comment by dot-agi** [comment]
> Suggestions
> 
> * 1. make this project in **Nextjs**
> * 2. Name: **Tech Swayamvar**
>      I think he suggested a really cool name😅
>      ![Screenshot_2023-04-12-23-33-18-182-edit_com twitter android](https://user-images.githubusercontent.com/53689208/231545285-c41a9ba2-a8cf-42a8-99a8-6573f8d47f7d.jpg)

From dating to swayamwar, things went 100x fast.

**Comment by dot-agi** [comment]
Here are my ideas:
* Dashboard to show analysis of any relationships dataset or extramarital affairs dataset. This is good for those who want to be skilled in data engineering, machine learning, and data analysis with a tinge of web dev/deployment.
* A website that tracks the commits of two people for the same repo to see their “commitment”. There can be additions to this such as the quality of commits, how quickly the commit was merged, etc
* A blind dating website and app where people only see each other's prompts, their views, etc, and are only allowed to upload pics that do not contain them (this is a good idea for CV enthusiasts to detect is the said person is in the image then prevent from uploading it).

Just my 2 cents.

**Comment by arnabnandy7** [comment]
> Here are my ideas:
> 
> * Dashboard to show analysis of any relationships dataset or extramarital affairs dataset. This is good for those who want to be skilled in data engineering, machine learning, and data analysis with a tinge of web dev/deployment.
> * A website that tracks the commits of two people for the same repo to see their “commitment”. There can be additions to this such as the quality of commits, how quickly the commit was merged, etc
> * A blind dating website and app where people only see each other's prompts, their views, etc, and are only allowed to upload pics that do not contain them (this is a good idea for CV enthusiasts to detect is the said person is in the image then prevent from uploading it).
> 
> Just my 2 cents.

- [ ] Anonymous statistics from the user base about their past relationships and why they didn't work out. Then create a comparative data analysis and dashboard consisting of charts to show the trends. It might be useful for upcoming candidates of relationships to avoid the least desirable feature of each other. Also, it should have this data basis on gender to know reasons that might vary between them and which reason was most prominent for each or any common case.
- [ ] A Statistics of the most desirable traits from the user base similarly (which people should develop to get into a relationship or those in the relationship need to hone it more to sustain), can have charts on comparative analysis between genders and the one trait which is common as well.

Some wild thoughts about the possible feature you can use to revolutionize your app might be to ensure it stands apart from current dating apps in terms of unique features which play around with the data. The data of course should be collected from the userbase with their consent to use it in an anonymous case study as whole consolidation which won't expose their information anyways.

**Comment by dot-agi** [comment]
@SayantaniDeb your thoughts?

> > Here are my ideas:
> > 
> > * Dashboard to show analysis of any relationships dataset or extramarital affairs dataset. This is good for those who want to be skilled in data engineering, machine learning, and data analysis with a tinge of web dev/deployment.
> > * A website that tracks the commits of two people for the same repo to see their “commitment”. There can be additions to this such as the quality of commits, how quickly the commit was merged, etc
> > * A blind dating website and app where people only see each other's prompts, their views, etc, and are only allowed to upload pics that do not contain them (this is a good idea for CV enthusiasts to detect is the said person is in the image then prevent from uploading it).
> > 
> > Just my 2 cents.
> 
> * [ ]  Anonymous statistics from the user base about their past relationships and why they didn't work out. Then create a comparative data analysis and dashboard consisting of charts to show the trends. It might be useful for upcoming candidates of relationships to avoid the least desirable feature of each other. Also, it should have this data basis on gender to know reasons that might vary between them and which reason was most prominent for each or any common case.
> * [ ]  A Statistics of the most desirable traits from the user base similarly (which people should develop to get into a relationship or those in the relationship need to hone it more to sustain), can have charts on comparative analysis between genders and the one trait which is common as well.
> 
> Some wild thoughts about the possible feature you can use to revolutionize your app might be to ensure it stands apart from current dating apps in terms of unique features which play around with the data. The data of course should be collected from the userbase with their consent to use it in an anonymous case study as whole consolidation which won't expose their information anyways.

**Comment by debasish-dutta** [comment]
Yes some stats regarding past failed relationships would be an wonderful feature to have. Using these people can avoid or desire such people. Plus if curated into a data set for further data analysis.
Also a recommendation engine!? suggesting the best possible mate depending upon one's own traits and wants or desires.

And maybe in future a cli as this is for developers so what better way then accessing from the terminal?

**Comment by arnabnandy7** [comment]
> recommendation engine

Primarily the idea is about not matching with other users but just showing them the trends or prominent suggestions at most. If users chose to go into it further then we can enable them for suggesting a match directly based on traits of both and likes/dislikes.

**Comment by SayantaniDeb** [comment]
Thank you guys for all the requested features, for further discussion i decided to head over to discord - https://discord.gg/Nhm6qY4GQf

Meets will be held weekly, if required.
Also, thank you for such amazing response on the idea implementation. Lets make it happen. 🫡
@arnabnandy7 @debasish-dutta @ashutosh7i @SrijanDas @the-praxs @subhams56
